{% set name = "murmurhash" %}
{% set version = "1.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 467b7ee31c1f79f46d00436a1957fc52a0e5801369dd2f30eb7655f380735b5f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.25
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - mmh3
    - pytest
    - pip
  imports:
    - murmurhash
    - murmurhash.mrmr
  commands:
    - pip check

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2
  dev_url: https://github.com/explosion/murmurhash/
  doc_url: https://github.com/explosion/murmurhash/

extra:
  recipe-maintainers:
    - rmax
    - ines
    - honnibal
    - adrianeboyd
