{% set name = "murmurhash" %}
{% set version = "0.28.0" %}
{% set sha256sum = "651137ed3e1169342c9edade454f3beb7fcdf28d4ad1ac232725237eaf442d9a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win32 or linux32]
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>34]

requirements:
  build:
    - toolchain
    - msinttypes  # [win and py<35]
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
