{% set name = "murmurhash" %}
{% set version = "1.0.7" %}
{% set sha256sum = "98ec9d727bd998a35385abd56b062cf0cca216725ea7ec5068604ab566f7e97f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - cython >=0.25
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - mmh3
    - pytest
    - pip
  imports:
    - murmurhash
    - murmurhash.mrmr
  commands:
    - pip check

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2
  dev_url: https://github.com/explosion/murmurhash/

extra:
  recipe-maintainers:
    - rmax
    - ines
    - honnibal
    - adrianeboyd