{% set name = "murmurhash" %}
{% set version = "1.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7a646f6b07b033642b4f52ae2e45efd8b80780b3b90e8092a0cec935fbf81e2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - msinttypes  # [win and vc<14]
    - python
    - pip
    - cython
    # setup.py constrains wheel via install_requires
    - wheel >=0.32.0,<0.33.0

  run:
    - python

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2
  doc_url: https://pypi.python.org/pypi/murmurhash
  doc_source_url: https://github.com/explosion/murmurhash/blob/master/README.rst
  dev_url: https://github.com/explosion/murmurhash

extra:
  recipe-maintainers:
    - rmax
