# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HGhGyTfKOa8AOPp7abSkQ41IT5hyAkbTm6JwopxcwFJ/E1jMRjqAoL3R/0wL+C7aqbIrjHNQVd7QNtmAilDbZO5UedxyEy7R97zKdgehgwCYBaRISobRFE8n5kXUH7J6dSj2ozOOFCZNtMQaC5yAvH8mYBa9b2lhM4ViKlveyOZeZfUcqdNWTUZzohSp7ppOE0LGZDOay0ZdTrxuo9wJowM7fm+nyGUHIbkNw+0iu26b37QZVQLhLWkVQ203zFI/4vfKHEoZWdP/e/oSxRHr6FzjIh6iqDiDi+cZ4/6RAga3Kuuu2LrGzJyFv/UHdlYqXzqg07pHQem3tlD0eAioGD78Nj+esoqDpZ9G5re1D7LDHCoIhIa+Aqg+KGzJ7a6XXNdc3hCaCGlg978HksdweeioUwxfZd/hrw4EZ42Uk3sB57szdntyqPCrewYAB/Ln1wIXjLJOw7xNx4DvexhO4BPEyZlLnsJd1V7A5wkAC2NuWsU6v2mnwcWGiPmvhSCQSMoN6GKsGS8HKf22sWNApm3XJQW2/GrcWdGvC0fKBElIByNgV6gauINcngfnlFid1giO7Kflez1Dan/c1TPLZPbVZmocQufi/Ll8/EBFBTiMcCqq8Bo3dE7FUbes/xBZWXjSkLeQ9qmQBfLEC50fl3VIzwn9N5GX6yaanBVVmz8="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
