travis:
  secure:
    BINSTAR_TOKEN: aLqtHKRrQH5IQYDVViQAowE1nwbnZ2TTKRC7fKZPBSv4cObN5BI+8AIhzJwtNUo1bW+2ZO5qnuIAAhymYhKoyBZxGqb9yfwnSES4DWyxhunZ35W9qVz+74/XeZzHUKVXn1o87nlT94FGFAH33QKXAQMKJnnnNm1Ay1NaNM/RxF//HLGg+qXMlbmOQQpYNQHdertBE7vLEAnNL8uCnIG9jCRUGBn8iqV4qihKiQ1bodsGJyM6HY9hNTwtIaqKqQqPYQQAcGPc/IVqY3nFunE55wor/LhQWSALFWkn7e05MMqFSzqoAt+C1vd3MMp/7lLNIoGtK/lz77aSSt6HTaihhopwYpz0XyPEKg5eC30dVF3uAp8MUTCmONb3gJ7EJX98nWWg2OiMRjLVPJi1ohVZLYmNXdEQtr065hXpTKDECJf+w06xSBF+Yht4/i2xH7t26apVYSWFLBihNVVrjLLli35tn6XntaIB5LMWBouURCFeg9Ohsk1JfkE5lNR/AXKJa1XZE4l5T96cCfnMJJrizk9F9fEbhU8QVpzFGWvlI8dkc1eW9/+jsGQCQQ3Sp1nC+djPo0r9wH3CpUfSyemYqjyeD6eoyM86kokXCy3/xbrtbbTA0fB8HS0kFYXgK+cCUeCBMvWsaXw7/70DnFBZwXqzfOgqP8KrRwPBEZUSG6I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
