travis:
  secure:
    BINSTAR_TOKEN: siOJlSCF5LT+6sFsbfrKgpo58jvnZN+DsIeRLzkbg1OTyyR/960gsc+Zue1bbEmmLHJ5DKeSm4hI9gJXyatA6HTAjr2umMJUCrXMc0MyHXDiWL8nI8PbO65bmxBQfbqAjtoDrmbzYnJ5ARRG9d0MpJFH42c04JUOhyZdt6OUOUp7WhJOM/YnwgSzuQq/J3aeuiiadak0QeQveb+C5GFWbqSui3Si6r7i+IZTR7S5+fHrnCF3LxDXkjqwbX9vnXuL1552thWORR+WidfO843A+km+Ac0q2B/REslL3eyFxlqPNK/LfDUhMngtvs3xHtZN/VqDM//nw/Gi6XnxB2GjbXc6t1sw8xKYAFSdQTXQnDBTjxkI3Ye1s4L1b+ZbJReb7d9FaeFA5KfUqLyTSTrSyHyuWVY9G0IKWY3KAZqsfaEbRrwjS+wKmQR49svuT82QTYsmWWMlzyqyiULHPZel/1hNC5sgSD/8Sb/vyA1svyZgJBmOPtk8Xw0vWDuc1iO39v8FTAQqBY4vABHS3Pxb5LH1eGIXHF5IB0XlAwu3sunkN49njkuk31gpV9Yy4UuW8QTLugardRRyhrLxksZwnjyORtEnPw8tOaQkVVZtCZXwFkBhgIXaCWld6W6Um4k8nLt34euqZitzP1G19qw7UeJhHMepe+/QcwNbX1rrLog=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
